# This workflow will do a clean install of python dependencies, run tests, build the docker images and deploy to Azure Container Instances

name: Build & Deploy

on:
  push:
    branches: [master]

jobs:
  build-client:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Publish Client to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        dockerfile: client/Dockerfile
        registry: atnuregistry.azurecr.io
        name: atnuregistry.azurecr.io/translations-client
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - name: Publish Server to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        dockerfile: server/Dockerfile
        registry: atnuregistry.azurecr.io
        name: atnuregistry.azurecr.io/translations-server
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
